server:
  persistentVolume:
    enabled: false

nodeExporter:
  enabled: true
  hostPort: false
  service:
    type: ClusterIP

extraScrapeConfigs: |
  - job_name: "api-server"
    static_configs:
      - targets: ["api-server.default.svc.cluster.local:8080"]
