server:
  service:
    type: NodePort
    nodePort: 31090

  persistentVolume:
    enabled: false

  configMaps:
    overrideName: prometheus-server

  serverFiles:
    prometheus.yml:
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: "prometheus"
          static_configs:
            - targets: ["localhost:9090"]
        - job_name: "api-server"
          static_configs:
            - targets: ["api-server.default.svc.cluster.local:8080"]
