apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-lab-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Taichi-iskw/infra-lab"
    targetRevision: HEAD
    path: infra/k8s/base
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
