service:
  type: NodePort
  nodePort: 31300

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/grafana/"
