apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: monitoring
    version: 25.21.0
    valuesFile: prometheus/prometheus-values.yaml

  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: monitoring
    version: 7.3.7
    valuesFile: grafana/grafana-values.yaml
