name: 🔧Go CI (API Server)
run-name: ${{ github.event.head_commit.message }}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
      - "apps/api-server/**"
  pull_request:
    branches: [main]
    paths:
      - "apps/api-server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/api-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
